### ISSUE TITLE
Issue with next page on search view

### ISSUE THREAD

**Issue by john-mcnamara-intel** [getpatchwork/patchwork#190] opened 2018-06-12 23:01 UTC
Hi,

If we run a search on the DPDK patchwork (version v2.0.2.post13-g29d7547) instance like this:

http://dpdk.org/dev/patchwork/project/dpdk/list/?series=&submitter=4&state=*&q=&archive=both&delegate=

We get the standard results page with several "Next page" options:

![aa_image](https://user-images.githubusercontent.com/12168946/41321564-03d13c3e-6e94-11e8-8cb3-56e7c870ed3d.png)

However, when we click on one of the page options, such as "2" we end up on a page with no next page options:

http://dpdk.org/dev/patchwork/project/dpdk/list/?submitter=4&state=*&page=2

![aa_image](https://user-images.githubusercontent.com/12168946/41321512-d685d000-6e93-11e8-8436-26081bf703d9.png)

The is possibly because some of the options in the query are now missing. The following, with `&page=2` added to the first query displays the next pages:

http://dpdk.org/dev/patchwork/project/dpdk/list/?series=&submitter=4&state=*&q=&archive=both&delegate=&page=2

Thanks,

John

**Comment by stephenfin** [comment] 2018-06-14 14:17
Thanks for the report, John. I'm closing as a duplicate of #184, which seems to capture the same issue you're seeing.

**Closed by stephenfin** 2018-06-14 14:17 UTC

**Comment by stephenfin** [comment] 2018-06-14 14:31
This is resolved in v2.0.3

**Comment by john-mcnamara-intel** [comment] 2018-06-14 14:41
Thanks Stephen. Sorry I missed the duplicate.
