### ISSUE TITLE
When each patch in the given series is archived `git pw series list` still shows the series in the question

### ISSUE THREAD

**Issue by andy-shev** [getpatchwork/patchwork#230] opened 2018-11-06 17:21 UTC
Server: patchwork.kernel.org
API: 1.1
Project: project/platform-driver-x86

So, since I have started using `git pw` (installed via `pip`), I see growing list of the series in `git pw series list` output. Because `git pw series` doesn't have an *update* feature, I'm archiving patches either via web, or via `pwclient` (may be old one).

Let's consider this series (most top in the project): `pwclient list -a no -f '%{id} %{state} %{delegate} %{name}'`

    10669785 Deferred 0andriy [V8,01/11] pvpanic: move pvpanic to misc as common driver
    10669797 Deferred 0andriy [v8,02/11] misc/pvpanic: simplify the code using acpi_dev_resource_io
    10669795 Deferred 0andriy [V8,03/11] misc/pvpanic: add MMIO support
    10669791 Deferred 0andriy [V8,04/11] dt-bindings: misc/pvpanic: add document for pvpanic-mmio
    10669799 Deferred 0andriy [V8,05/11] misc/pvpanic: add support to get pvpanic device info FDT
    10669805 Deferred 0andriy [V8,06/11] misc/pvpanic : grouping ACPI related stuff
    10669807 Deferred 0andriy [V8,07/11] misc/pvpanic : break dependency on ACPI
    10669787 Deferred 0andriy [V8,08/11] misc/pvpanic: remove unnecessary header file
    10669793 Deferred 0andriy [V8,09/11] misc/pvpanic: change header file sort style
    10669809 Deferred 0andriy [V8,10/11] misc/pvpanic: convert to SPDX license tags
    10669789 Deferred 0andriy [V8,11/11] misc/pvpanic: remove a redundant comma

`git pw series list` output:

    | 39017 | 2 hours ago | [V8,01/11] pvpanic: move pvpanic to misc as common driver                |         8 | Peng Hao (peng.hao2@zte.com.cn)                        |

I run the following command: `pwclient update -a yes $(pwclient list -a no -s Deferred -f '%{id}')`

In the result, the output of `git pw series list` hadn't been changed.

**Comment by ajdlinux** [comment] 2019-11-27 04:01
Related: #157

**Comment by stephenfin** [comment] 2019-11-27 09:11
Good catch. I'm going to close this as a duplicate of #157.

**Closed by stephenfin** 2019-11-27 09:11 UTC
Labels: enhancement
