### ISSUE TITLE
Patch subjects with commas are corrupted

### ISSUE THREAD

**Issue by robherring** [getpatchwork/patchwork#197] opened 2018-07-16 16:55 UTC
Patchwork is inserting a space after a comma in the subject.

    "dt-bindings: sound: wm8994: document wlf, csnaddr-pd property"

while the version I've received via the maillist is correct:

    "dt-bindings: sound: wm8994: document wlf,csnaddr-pd property"

This example can be found here: http://patchwork.ozlabs.org/patch/941526/

Looking at the headers, it seems all the headers get line wrapped after a comma which causes the problem.

**Comment by peda-r** [comment] 2018-08-27 20:50
Another annoying hit
https://patchwork.freedesktop.org/patch/246039/

**Comment by stephenfin** [comment] 2018-10-06 21:45
I'm marking this as an enhancement rather than a bug. Ideally we should store the raw, unmodified subject. That's not something we'll be able to address until 2.2 at the earliest though.

**Comment by stephenfin** [comment] 2018-11-04 13:32
@robherring Would it be possible to get a copy of the mbox from the mailing list? I haven't been able to reproduce this.

**Comment by robherring** [comment] 2018-11-04 14:54
Here's the same message I originally referenced.

[msg.txt](https://github.com/getpatchwork/patchwork/files/2545926/msg.txt)

**Closed** 2018-12-22 18:08 UTC
Labels: bug

**Comment by jk-ozlabs** [comment] 2019-05-14 00:53
This fix doesn't look correct to me. The core of that change is:

``` value = ''.join(re.split(r'\n\s+', value)) ```

(ie, where we find a newline followed by a space, remove the newline and the space)

However, from RFC2822, section 2.2.3:

> Unfolding is accomplished by simply removing any CRLF
>   that is immediately followed by WSP.

With the fix as it is, the example quoted in the RFC:

```
Subject: This
 is a test
```

Will be transformed in to:

```
Subject: Thisis a test
```

Which is what has happened here:

https://patchwork.ozlabs.org/patch/1097852/

**Comment by robherring** [comment] 2019-05-20 14:07
Going to re-open this since the commit was reverted?

**Comment by daxtens** [comment] 2019-05-20 14:33
The corruption seems to have been caused by a preprocessing layer unique to
OzLabs, which I am told has since been fixed by upgrading it to Python3.
Are you seeing this corruption in any new messages?

**Comment by robherring** [comment] 2019-05-20 15:48
@daxtens I realized this just after commenting, so I deleted my comment. I don't think @jk-ozlabs has picked up this revert and reworked the filtering.
