### ISSUE TITLE
Disambiguate users with the same (rewritten) From address

### ISSUE THREAD

**Issue by 0xabu** [getpatchwork/patchwork#158] opened 2018-01-12 21:43 UTC
The following list of patches look like they're all mine in patchwork, but they're mostly not:
https://patchwork.kernel.org/project/qemu-devel/list/?submitter=173467

This happens because qemu-devel is sometimes forced to rewrite the From address to avoid problems with DKIM signatures (explained in gory detail [here](https://lists.gnu.org/archive/html/qemu-devel/2017-03/msg05625.html)), e.g.:
```
From: "Andrew Baumann via Qemu-devel" <qemu-devel@nongnu.org>
```

Since mine was the first patch/email patchwork saw with that address, it now treats all patches with a From address of qemu-devel@nongnu.org as mine. Perhaps the easiest fix to disambiguate cases like this might be to use the entire value of the From header?

**Comment by stephenfin** [comment] 2019-10-18 06:12
I _think_ this is a dupe of #64, which should be reolved by a [recent change](https://github.com/getpatchwork/patchwork/commit/8279a84238c10acbcadd075e4e998dffdc39f2e9) to better handle `From` lines mangled for DMARC purposes

**Closed by stephenfin** 2019-10-18 06:12 UTC
Labels: enhancement, help wanted
